-- storage/init.sql
-- PostgreSQL schema for the real-time fraud alert store (flagged_transactions)

CREATE TABLE IF NOT EXISTS flagged_transactions (
    -- Surrogate key. Spark's JDBC writer never populates this column (it
    -- only inserts the columns present in the DataFrame), so Postgres
    -- assigns it automatically on every insert — no pipeline change needed.
    id                      BIGSERIAL PRIMARY KEY,

    -- Business identifier generated by the PaySim producer (producer.py:
    -- transaction_id = str(uuid.uuid4())). Stored as text because Spark's
    -- TRANSACTION_SCHEMA declares it StringType; casting to native UUID
    -- would require a code change on the Spark side (see rationale doc).
    transaction_id          VARCHAR(36)  NOT NULL,

    account_origin          VARCHAR(20)  NOT NULL,

    -- Spark writes these as DoubleType (F.round(..., 2)). DOUBLE PRECISION
    -- matches the real current pipeline. NUMERIC(15,2) would be the more
    -- defensible type for financial data long-term — flagged as a follow-up
    -- in DATA_MODEL.md rather than silently "fixed" here.
    amount                  DOUBLE PRECISION NOT NULL,
    balance_orig_before     DOUBLE PRECISION NOT NULL,
    balance_orig_after      DOUBLE PRECISION NOT NULL,

    transaction_type        VARCHAR(20)  NOT NULL,

    -- One of: ACCOUNT_EMPTIED, LARGE_AMOUNT, BALANCE_MISMATCH
    -- (fraud_detector.py: rule_name literals passed into add_alert_columns)
    rule_triggered          VARCHAR(30)  NOT NULL,

    -- Hardcoded severity per rule in fraud_detector.py (85 / 80 / 90)
    risk_score              SMALLINT     NOT NULL CHECK (risk_score BETWEEN 0 AND 100),

    alert_reason            TEXT         NOT NULL,

    -- Ground-truth fraud label carried through from the PaySim simulator.
    -- Only exists because this is a portfolio/simulation pipeline — a real
    -- production feed would not have this label available at alert time.
    is_fraud                SMALLINT     NOT NULL CHECK (is_fraud IN (0, 1)),

    -- F.current_timestamp() at the moment Spark evaluated the micro-batch
    detected_at             TIMESTAMP    NOT NULL,

    -- Row insert time in Postgres itself, independent of Spark's clock —
    -- useful for measuring detection-to-storage latency.
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_transaction_rule UNIQUE (transaction_id, rule_triggered)
);

-- Supports the Power BI / dashboard query pattern already in the README
-- ("SELECT rule_triggered, COUNT(*) ... GROUP BY rule_triggered")
CREATE INDEX IF NOT EXISTS idx_flagged_rule_triggered
    ON flagged_transactions (rule_triggered);

-- Supports time-windowed alert queries (e.g. "alerts in the last hour")
CREATE INDEX IF NOT EXISTS idx_flagged_detected_at
    ON flagged_transactions (detected_at);

COMMENT ON TABLE flagged_transactions IS
    'Operational alert log. Exception-based store: only transactions that '
    'trip one of the 3 SQL-derived detection rules are written here. The '
    'full transaction stream is not persisted in Postgres — it exists '
    'transiently in the Kafka topic paysim_transactions (168h retention per '
    'docker-compose.yml KAFKA_LOG_RETENTION_HOURS), then is replayed '
    'through 3 parallel Spark Structured Streaming queries.';
